### ISSUE TITLE
Publish as a Firefox extension

### ISSUE THREAD

**Issue by zackschuster** [ofrobots/typescript-friendly#6]
As of version 57, Firefox officially supports the same WebExtension format as Chrome; as such, it shouldn't be too hard (if it requires any effort at all) to port over.

**Comment by ofrobots** [comment]
Thanks for raising the issue, let me look into it :).

**Comment by ofrobots** [comment]
Published here: https://addons.mozilla.org/en-US/firefox/addon/typescript-friendly/
