### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by styfle** [ofrobots/typescript-friendly#9]
I just wanted to say thanks for a great tool!

It also helped me better understand the npm API so I could build [Package Phobia](https://github.com/styfle/packagephobia) which is of course, written in TypeScript 😄

**Comment by ofrobots** [comment]
Package Phobia looks really nice, well done! Looks like it is complimentary to another thing I made: https://www.npmjs.com/package/require-so-slow. I want to convert to an online version next, and would take some inspiration from Package Phobia!

**Comment by styfle** [comment]
Wow that is really cool! And now I understand the purpose of `perf_hooks`.
I'll add a link in the readme since this might be useful for users of Package Phobia.

Also, thank you for the kind words 😄
